[project]
name = "explore_llm_fine_tuning"
version = "0.1.0"
description = "Explore various techniques for fine-tuning large language models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
